---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

downstream_package_name: netavark
upstream_tag_template: v{version}

packages:
  netavark-fedora:
    pkg_tool: fedpkg
    specfile_path: rpm/netavark.spec
  netavark-centos:
    pkg_tool: centpkg
    specfile_path: rpm/netavark.spec
  netavark-rhel:
    specfile_path: rpm/netavark.spec

srpm_build_deps:
  - cargo
  - make
  - openssl-devel

jobs:
  - job: copr_build
    trigger: pull_request
    packages: [netavark-fedora]
    notifications: &copr_build_failure_notification
      failure_comment:
        message: "Ephemeral COPR build failed. @containers/packit-build please check."
    targets:
      fedora-all-x86_64: {}
      fedora-all-aarch64: {}
      fedora-eln-x86_64:
        additional_repos:
          - "https://kojipkgs.fedoraproject.org/repos/eln-build/latest/x86_64/"
      fedora-eln-aarch64:
        additional_repos:
          - "https://kojipkgs.fedoraproject.org/repos/eln-build/latest/aarch64/"
    enable_net: true

  - job: copr_build
    trigger: pull_request
    packages: [netavark-centos]
    notifications: *copr_build_failure_notification
    targets:
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
      - centos-stream-10-x86_64
      - centos-stream-10-aarch64
    enable_net: true

  - job: copr_build
    trigger: pull_request
    packages: [netavark-rhel]
    notifications: *copr_build_failure_notification
    targets:
      - epel-9-x86_64
      - epel-9-aarch64
    enable_net: true

  # Run on commit to main branch
  - job: copr_build
    trigger: commit
    packages: [netavark-fedora]
    notifications:
      failure_comment:
        message: "podman-next COPR build failed. @containers/packit-build please check."
    branch: main
    owner: rhcontainerbot
    project: podman-next
    enable_net: true

  # Sync to Fedora
  - job: propose_downstream
    trigger: release
    packages: [netavark-fedora]
    update_release: false
    dist_git_branches:
      - fedora-all

  # Sync to CentOS Stream
  - job: propose_downstream
    trigger: release
    packages: [netavark-centos]
    update_release: false
    dist_git_branches:
      - c10s

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

        # NOTE: Bodhi update tasks are disabled to allow netavark and aardvark-dns X.Y
        # builds in a single manual bodhi update. Leaving this commented out
        # but not deleted so it's not forgotten.
        #- job: bodhi_update
        #trigger: commit
        #dist_git_branches:
        #- fedora-branched # rawhide updates are created automatically
